steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - $LOCATION-docker.pkg.dev/${PROJECT_ID}/$LOCATION/angular18-img:${SHORT_SHA}'
      # - '--build-arg'
      # - 'APP_ENV=${_APP_ENV}'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - $LOCATION-docker.pkg.dev/${PROJECT_ID}/$LOCATION/angular18-img:${SHORT_SHA}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${REPO_NAME}'
      - '--image$LOCATION-docker.pkg.dev/${PROJECT_ID}/$LOCATION/angular18-img:${SHORT_SHA}'
      - '--region=$LOCATION'
      - '--platform=managed'
      - '--ingress=all'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

