steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$LOCATION-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}'
      - '--build-arg'
      - 'APP_ENV=${_APP_ENV}'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$LOCATION-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${REPO_NAME}'
      - '--image=$LOCATION-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}'
      - '--region=$LOCATION'
      - '--platform=managed'
      - '--ingress=all'
      - '--allow-unauthenticated'

images:
  - '$LOCATION-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY

